In [14]:
import numpy as np

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
reshaped=arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
flattend=reshaped.flatten()
flattend

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
flattend=reshaped.flatten()
flattend[0]=99
flattend

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
raveled=reshaped.ravel()
raveled[1]=88
raveled

array([ 1, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
reshaped

array([[ 1, 88,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr1=np.array([1,2,3])
arr1
arr2=np.array([2,3,4])
arr2

array([2, 3, 4])

In [23]:
arr=8
arr=9

In [26]:
np.array([10,11,12,13,14,15,16,17,18,19,20,21])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [27]:
arr1=np.array([1,2,3])
arr1
arr2=np.array([[2],[4],[6]])
arr2

array([[2],
       [4],
       [6]])

In [28]:
arr1+arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [29]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])